import { describe, expect, it } from 'vitest';

import {
  generateQualityReport,
  renderHtml,
  renderJson,
  renderMarkdown,
  DefaultMarkdownReportRenderer,
  DefaultHtmlReportRenderer,
  DefaultJsonReportRenderer,
  MARKDOWN_RENDERER_VERSION,
  HTML_RENDERER_VERSION,
  JSON_RENDERER_VERSION,
  type QualityReportInput,
  type UIQualityReport,
} from '@uiq/reporting';

import { makeDiagnostic, makeEvaluation, makeFinding, makeFacts } from './helpers';

const ENGINE = { name: '@uiq/metrics', version: '1.0.0' } as const;
const OPTIONS = { generatedAt: '2026-09-24T00:00:00.000Z' } as const;

function reportInput(parts?: {
  projectId?: string;
  findings?: ReturnType<typeof makeFinding>[];
  evaluations?: ReturnType<typeof makeEvaluation>[];
  diagnostics?: ReturnType<typeof makeDiagnostic>[];
  themeId?: string;
}): QualityReportInput {
  const facts = makeFacts({
    evaluations: parts?.evaluations ?? [makeEvaluation()],
    findings: parts?.findings ?? [],
    diagnostics: parts?.diagnostics ?? [],
  });
  return {
    projectId: parts?.projectId ?? 'proj-1',
    snapshot: facts.snapshot,
    metricResults: facts.metricResults,
    evaluations: facts.evaluations,
    findings: facts.findings,
    diagnostics: facts.diagnostics,
    engine: ENGINE,
    ...(parts?.themeId !== undefined ? { themeId: parts.themeId } : {}),
  };
}

function makeReport(parts?: {
  findings?: ReturnType<typeof makeFinding>[];
  evaluations?: ReturnType<typeof makeEvaluation>[];
  diagnostics?: ReturnType<typeof makeDiagnostic>[];
}): UIQualityReport {
  return generateQualityReport(reportInput(parts), OPTIONS);
}

// ─── AC-IMPL32-01: Markdown Renderer 实现 ──────────────────────────

describe('IMPL-32 Markdown Renderer（AC-IMPL32-01）', () => {
  it('输出包含所有必需章节标题', () => {
    const report = makeReport();
    const md = renderMarkdown(report);
    for (const heading of [
      '# UI Quality Assessment Report',
      '## 1. Report Metadata',
      '## 2. Executive Summary',
      '## 3. Measurement Coverage',
      '## 4. Quality Dimensions',
      '## 5. Visual Texture',
      '## 6. Findings',
      '## 7. Diagnostics',
      '## 8. Conformance',
      '## 9. Regression Analysis',
      '## 10. Improvement Recommendations',
      '## 11. Verification Criteria',
      '## 12. Release Gate',
      '## 13. Reproducibility',
    ]) {
      expect(md).toContain(heading);
    }
  });

  it('包含 Generated by UIQ 头部', () => {
    const md = renderMarkdown(makeReport());
    expect(md).toContain('> Generated by UIQ 1.0.0');
  });

  it('Metadata 表格包含关键字段', () => {
    const md = renderMarkdown(makeReport());
    expect(md).toContain('| Project |');
    expect(md).toContain('| UIQ Version |');
    expect(md).toContain('| Engine Version |');
    expect(md).toContain('| Generated At |');
  });

  it('Executive Summary 包含 Evaluation 表格', () => {
    const md = renderMarkdown(makeReport());
    expect(md).toContain('| State | Count |');
    expect(md).toContain('| PASS |');
    expect(md).toContain('| FAIL |');
    expect(md).toContain('| UNKNOWN |');
  });

  it('Visual Texture 固定七维（AC-IMPL32-14）', () => {
    const md = renderMarkdown(makeReport());
    expect(md).toContain('### 5.1 Surface');
    expect(md).toContain('### 5.2 Depth');
    expect(md).toContain('### 5.3 Color');
    expect(md).toContain('### 5.4 Typography');
    expect(md).toContain('### 5.5 Spatial');
    expect(md).toContain('### 5.6 Motion');
    expect(md).toContain('### 5.7 Micro Detail');
  });

  it('Findings 表格包含列头', () => {
    const report = makeReport({
      findings: [
        makeFinding({
          id: 'F-001',
          evaluation: makeEvaluation({ state: 'FAIL', severity: 'HIGH' }),
        }),
      ],
    });
    const md = renderMarkdown(report);
    expect(md).toContain('| ID | Type | Severity | Subject | Rule | State |');
    expect(md).toContain('F-001');
  });

  it('空章节不隐藏（§42），显示空消息', () => {
    const md = renderMarkdown(makeReport());
    expect(md).toContain('No findings were generated');
    expect(md).toContain('No diagnostics were generated');
    expect(md).toContain('No improvement recommendations');
  });

  it('Conformance 未执行时显示诚实消息', () => {
    const md = renderMarkdown(makeReport());
    expect(md).toContain('Conformance evaluation was not performed');
  });

  it('Regression 未执行时显示诚实消息', () => {
    const md = renderMarkdown(makeReport());
    expect(md).toContain('Regression analysis was not performed');
  });

  it('不生成 Overall Score（§13）', () => {
    const md = renderMarkdown(makeReport());
    expect(md).not.toContain('Overall UI Quality');
    expect(md).not.toContain('Visual Quality:');
    expect(md).not.toMatch(/\d+\.\d+\/10/);
  });
});

// ─── AC-IMPL32-02: HTML Renderer 实现 ──────────────────────────────

describe('IMPL-32 HTML Renderer（AC-IMPL32-02）', () => {
  it('输出完整 HTML 文档结构', () => {
    const html = renderHtml(makeReport());
    expect(html).toContain('<!DOCTYPE html>');
    expect(html).toContain('<html lang="en">');
    expect(html).toContain('<meta charset="utf-8">');
    expect(html).toContain('</html>');
  });

  it('单文件自包含：无外部依赖（§36）', () => {
    const html = renderHtml(makeReport());
    expect(html).not.toContain('cdn.');
    expect(html).not.toContain('href="http');
    expect(html).not.toContain('src="http');
    expect(html).toContain('<style>');
  });

  it('包含所有语义化 section', () => {
    const html = renderHtml(makeReport());
    expect(html).toContain('<header>');
    expect(html).toContain('<main>');
    expect(html).toContain('id="metadata"');
    expect(html).toContain('id="summary"');
    expect(html).toContain('id="dimensions"');
    expect(html).toContain('id="visual-texture"');
    expect(html).toContain('id="findings"');
    expect(html).toContain('id="diagnostics"');
    expect(html).toContain('id="conformance"');
    expect(html).toContain('id="regression"');
    expect(html).toContain('id="recommendations"');
    expect(html).toContain('id="verification"');
    expect(html).toContain('id="release-gate"');
    expect(html).toContain('id="reproducibility"');
  });

  it('表格包含 scope="col" 表头（§39 Accessibility）', () => {
    const html = renderHtml(makeReport());
    expect(html).toContain('scope="col"');
  });

  it('包含 details/summary 可折叠交互（§38）', () => {
    const report = makeReport({
      findings: [
        makeFinding({
          id: 'F-001',
          evaluation: makeEvaluation({ state: 'FAIL', severity: 'HIGH' }),
        }),
      ],
    });
    const html = renderHtml(report);
    expect(html).toContain('<details>');
    expect(html).toContain('<summary>');
  });
});

// ─── AC-IMPL32-03: JSON Renderer 实现 ──────────────────────────────

describe('IMPL-32 JSON Renderer（AC-IMPL32-03）', () => {
  it('输出可解析为等价对象', () => {
    const report = makeReport();
    const json = renderJson(report);
    expect(JSON.parse(json)).toEqual(report);
  });
});

// ─── AC-IMPL32-04: 三个 Renderer 共用 UIQualityReport ──────────────

describe('IMPL-32 共用 UIQualityReport（AC-IMPL32-04）', () => {
  it('同一 report 可被三个 Renderer 渲染', () => {
    const report = makeReport();
    const md = renderMarkdown(report);
    const html = renderHtml(report);
    const json = renderJson(report);
    expect(typeof md).toBe('string');
    expect(typeof html).toBe('string');
    expect(typeof json).toBe('string');
    expect(md.length).toBeGreaterThan(0);
    expect(html.length).toBeGreaterThan(0);
    expect(json.length).toBeGreaterThan(0);
  });
});

// ─── AC-IMPL32-05/06/07/08: Renderer 不执行 Metric/Rule/Finding/Recommendation ─

describe('IMPL-32 Renderer 纯函数约束（AC-IMPL32-05~08）', () => {
  it('Renderer 类实例只调用 render 不产生副作用', () => {
    const mdRenderer = new DefaultMarkdownReportRenderer();
    const htmlRenderer = new DefaultHtmlReportRenderer();
    const jsonRenderer = new DefaultJsonReportRenderer();
    const report = makeReport();
    // 两次渲染结果相同
    expect(mdRenderer.render(report)).toBe(mdRenderer.render(report));
    expect(htmlRenderer.render(report)).toBe(htmlRenderer.render(report));
    expect(jsonRenderer.render(report)).toBe(jsonRenderer.render(report));
  });
});

// ─── AC-IMPL32-09/10: Markdown/HTML 结构完整 ───────────────────────

describe('IMPL-32 结构完整性（AC-IMPL32-09/10）', () => {
  it('Markdown Coverage 表格存在', () => {
    const md = renderMarkdown(makeReport());
    expect(md).toContain('## 3. Measurement Coverage');
    expect(md).toContain('Coverage');
  });

  it('HTML 包含 Visual Texture 七维', () => {
    const html = renderHtml(makeReport());
    expect(html).toContain('Surface');
    expect(html).toContain('Depth');
    expect(html).toContain('Color');
    expect(html).toContain('Typography');
    expect(html).toContain('Spatial');
    expect(html).toContain('Motion');
    expect(html).toContain('Micro Detail');
  });
});

// ─── AC-IMPL32-27: XSS / Injection Test ────────────────────────────

describe('IMPL-32 安全性（AC-IMPL32-27）', () => {
  it('Markdown: <script> 被转义（§58）', () => {
    const hostile = '<script>alert(1)</script>';
    const report = makeReport({
      findings: [
        makeFinding({
          id: 'f1',
          subjectId: hostile,
          evaluation: makeEvaluation({ subjectId: hostile, state: 'FAIL', severity: 'HIGH' }),
        }),
      ],
    });
    const md = renderMarkdown(report);
    expect(md).not.toContain('<script>');
    expect(md).toContain('&lt;script&gt;');
  });

  it('HTML: <script> 被转义（§59）', () => {
    const hostile = '<script>alert(1)</script>';
    const report = makeReport({
      findings: [
        makeFinding({
          id: 'f1',
          subjectId: hostile,
          evaluation: makeEvaluation({ subjectId: hostile, state: 'FAIL', severity: 'HIGH' }),
        }),
      ],
    });
    const html = renderHtml(report);
    expect(html).not.toContain('<script>alert');
    expect(html).toContain('&lt;script&gt;');
  });
});

// ─── AC-IMPL32-28: Determinism Test ────────────────────────────────

describe('IMPL-32 确定性（AC-IMPL32-28）', () => {
  it('同 report 两次 Markdown 输出完全相同', () => {
    const report = makeReport({
      findings: [makeFinding({ id: 'f1' })],
    });
    expect(renderMarkdown(report)).toBe(renderMarkdown(report));
  });

  it('同 report 两次 HTML 输出完全相同', () => {
    const report = makeReport({
      findings: [makeFinding({ id: 'f1' })],
    });
    expect(renderHtml(report)).toBe(renderHtml(report));
  });

  it('同 report 两次 JSON 输出完全相同', () => {
    const report = makeReport({
      findings: [makeFinding({ id: 'f1' })],
    });
    expect(renderJson(report)).toBe(renderJson(report));
  });
});

// ─── Renderer 版本（§49） ──────────────────────────────────────────

describe('IMPL-32 Renderer 版本（§49）', () => {
  it('Markdown Renderer 版本为 1.0.0', () => {
    expect(MARKDOWN_RENDERER_VERSION).toBe('1.0.0');
  });

  it('HTML Renderer 版本为 1.0.0', () => {
    expect(HTML_RENDERER_VERSION).toBe('1.0.0');
  });

  it('JSON Renderer 版本为 1.0.0', () => {
    expect(JSON_RENDERER_VERSION).toBe('1.0.0');
  });
});

// ─── Release Gate 派生逻辑 ─────────────────────────────────────────

describe('IMPL-32 Release Gate 派生', () => {
  it('无 findings → PASS', () => {
    const md = renderMarkdown(makeReport());
    expect(md).toContain('**Status:** PASS');
  });

  it('有 HIGH severity findings → WARN', () => {
    const report = makeReport({
      findings: [
        makeFinding({
          id: 'f1',
          severity: 'HIGH',
          evaluation: makeEvaluation({ state: 'FAIL', severity: 'HIGH' }),
        }),
      ],
    });
    const md = renderMarkdown(report);
    expect(md).toContain('**Status:** WARN');
  });
});

// ─── Recommendation 原则（§26） ────────────────────────────────────

describe('IMPL-32 Recommendation 原则（§26）', () => {
  it('Recommendation 不包含自动修复值', () => {
    const md = renderMarkdown(makeReport());
    // 不应出现 "Change #xxx to #yyy" 类文本
    expect(md).not.toMatch(/Change #[0-9a-fA-F]+ to #[0-9a-fA-F]+/);
  });
});
