import type { EnrichedRuleDefinition } from '../../evaluation/engine';
import {
  COLOR_LIGHTNESS_HIERARCHY_RULE, COLOR_CHROMA_DISTRIBUTION_RULE, COLOR_HUE_RELATIONSHIP_RULE,
  COLOR_HARMONY_RULE, COLOR_TOKEN_CONSISTENCY_RULE, COLOR_NOISE_RULE, COLOR_CONTRAST_QUALITY_RULE,
} from './rules';

export const colorTextureRules: readonly EnrichedRuleDefinition[] = [
  COLOR_LIGHTNESS_HIERARCHY_RULE, COLOR_CHROMA_DISTRIBUTION_RULE, COLOR_HUE_RELATIONSHIP_RULE,
  COLOR_HARMONY_RULE, COLOR_TOKEN_CONSISTENCY_RULE, COLOR_NOISE_RULE, COLOR_CONTRAST_QUALITY_RULE,
] as const;

export {
  COLOR_LIGHTNESS_HIERARCHY_RULE, COLOR_CHROMA_DISTRIBUTION_RULE, COLOR_HUE_RELATIONSHIP_RULE,
  COLOR_HARMONY_RULE, COLOR_TOKEN_CONSISTENCY_RULE, COLOR_NOISE_RULE, COLOR_CONTRAST_QUALITY_RULE,
};
