import type { EnrichedRuleDefinition } from '../../evaluation/engine';
import {
  MICRO_STATE_COMPLETENESS_RULE, MICRO_COMPONENT_CONSISTENCY_RULE, MICRO_ICON_CONSISTENCY_RULE,
  MICRO_FOCUS_QUALITY_RULE, MICRO_DISABLED_QUALITY_RULE, MICRO_EMPTY_QUALITY_RULE,
  MICRO_BORDER_DETAIL_RULE, MICRO_RADIUS_DETAIL_RULE, MICRO_LOADING_QUALITY_RULE, MICRO_ERROR_QUALITY_RULE,
  MICRO_HOVER_COMPLETENESS_RULE, MICRO_ACTIVE_FEEDBACK_RULE, MICRO_SELECTED_DIFFERENTIATION_RULE,
  MICRO_ICON_ALIGNMENT_RULE, MICRO_COMPONENT_DENSITY_RULE, MICRO_FRAGMENTATION_RULE,
} from './rules';

export const microDetailTextureRules: readonly EnrichedRuleDefinition[] = [
  MICRO_STATE_COMPLETENESS_RULE, MICRO_COMPONENT_CONSISTENCY_RULE, MICRO_ICON_CONSISTENCY_RULE,
  MICRO_FOCUS_QUALITY_RULE, MICRO_DISABLED_QUALITY_RULE, MICRO_EMPTY_QUALITY_RULE,
  MICRO_BORDER_DETAIL_RULE, MICRO_RADIUS_DETAIL_RULE, MICRO_LOADING_QUALITY_RULE, MICRO_ERROR_QUALITY_RULE,
  MICRO_HOVER_COMPLETENESS_RULE, MICRO_ACTIVE_FEEDBACK_RULE, MICRO_SELECTED_DIFFERENTIATION_RULE,
  MICRO_ICON_ALIGNMENT_RULE, MICRO_COMPONENT_DENSITY_RULE, MICRO_FRAGMENTATION_RULE,
] as const;

export {
  MICRO_STATE_COMPLETENESS_RULE, MICRO_COMPONENT_CONSISTENCY_RULE, MICRO_ICON_CONSISTENCY_RULE,
  MICRO_FOCUS_QUALITY_RULE, MICRO_DISABLED_QUALITY_RULE, MICRO_EMPTY_QUALITY_RULE,
  MICRO_BORDER_DETAIL_RULE, MICRO_RADIUS_DETAIL_RULE, MICRO_LOADING_QUALITY_RULE, MICRO_ERROR_QUALITY_RULE,
  MICRO_HOVER_COMPLETENESS_RULE, MICRO_ACTIVE_FEEDBACK_RULE, MICRO_SELECTED_DIFFERENTIATION_RULE,
  MICRO_ICON_ALIGNMENT_RULE, MICRO_COMPONENT_DENSITY_RULE, MICRO_FRAGMENTATION_RULE,
};
