/**
 * Markdown 报告各章节渲染（IMPL-32 §8-33）。
 *
 * 报告模板固定顺序（§41）：
 * Metadata → Summary → Coverage → Dimensions → Visual Texture →
 * Findings → Diagnostics → Conformance → Regression → Recommendations →
 * Verification → Release Gate → Reproducibility
 *
 * 空章节不隐藏（§42），UNKNOWN/ERROR 独立呈现（§43-45）。
 */
import type { UIQualityReport } from '../../model/report';
import { escapeMarkdown, escapeTableCell } from './escape';

function joinList(items: readonly string[]): string {
  return items.length > 0 ? items.join(', ') : 'none';
}

// ─── §10-11 Metadata ──────────────────────────────────────────────

export function renderHeader(report: UIQualityReport): string {
  const lines: string[] = [];
  lines.push('# UI Quality Assessment Report');
  lines.push('');
  lines.push(`> Generated by UIQ ${escapeMarkdown(report.version)}`);
  lines.push('');
  return lines.join('\n');
}

export function renderMetadata(report: UIQualityReport): string {
  const lines: string[] = [];
  lines.push('## 1. Report Metadata');
  lines.push('');
  lines.push('| Property | Value |');
  lines.push('|---|---|');
  lines.push(`| Project | ${escapeTableCell(report.projectId)} |`);
  lines.push(`| UIQ Version | ${escapeTableCell(report.version)} |`);
  lines.push(`| Engine Version | ${escapeTableCell(report.reproducibility.engine.version)} |`);
  lines.push(
    `| Viewport | ${escapeTableCell(report.scope.viewports.length > 0 ? report.scope.viewports.join(', ') : 'N/A')} |`,
  );
  lines.push(`| Theme | ${escapeTableCell(report.scope.themes.length > 0 ? report.scope.themes.join(', ') : 'N/A')} |`);
  lines.push(
    `| Snapshot | ${escapeTableCell(report.scope.snapshotIds.length > 0 ? report.scope.snapshotIds.join(', ') : 'N/A')} |`,
  );
  lines.push(`| Generated At | ${escapeMarkdown(report.generatedAt)} |`);
  lines.push('');
  return lines.join('\n');
}

// ─── §12 Executive Summary ─────────────────────────────────────────

export function renderSummary(report: UIQualityReport): string {
  const s = report.summary;
  const lines: string[] = [];
  lines.push('## 2. Executive Summary');
  lines.push('');
  lines.push('### Scope');
  lines.push('');
  lines.push(`- Pages: ${report.scope.snapshotIds.length}`);
  lines.push(`- Elements: ${s.measuredElements}`);
  lines.push(`- Components: ${report.scope.subjects.length}`);
  lines.push(`- Themes: ${report.scope.themes.length}`);
  lines.push('');
  lines.push('### Evaluation');
  lines.push('');
  lines.push('| State | Count |');
  lines.push('|---|---:|');
  lines.push(`| PASS | ${s.pass} |`);
  lines.push(`| FAIL | ${s.fail} |`);
  lines.push(`| WARN | ${s.warn} |`);
  lines.push(`| UNKNOWN | ${s.unknown} |`);
  lines.push(`| NOT_APPLICABLE | ${s.notApplicable} |`);
  lines.push(`| ERROR | ${s.error} |`);
  lines.push('');
  return lines.join('\n');
}

// ─── §14 Measurement Coverage ──────────────────────────────────────

export function renderCoverage(report: UIQualityReport): string {
  const lines: string[] = [];
  lines.push('## 3. Measurement Coverage');
  lines.push('');
  lines.push('| Dimension | Elements | Evaluations | Unknown | Coverage |');
  lines.push('|---|---:|---:|---:|---:|');
  for (const d of report.dimensions) {
    const total = d.evaluations;
    const coverage = total > 0 ? (((total - d.unknown) / total) * 100).toFixed(1) : '100.0';
    lines.push(
      `| ${escapeTableCell(d.dimension)} | ${d.evaluations} | ${d.evaluations} | ${d.unknown} | ${coverage}% |`,
    );
  }
  if (report.dimensions.length === 0) {
    lines.push('| — | — | — | — | — |');
  }
  lines.push('');
  return lines.join('\n');
}

// ─── §15-16 Quality Dimensions ─────────────────────────────────────

export function renderDimensions(report: UIQualityReport): string {
  const lines: string[] = [];
  lines.push('## 4. Quality Dimensions');
  lines.push('');
  if (report.dimensions.length === 0) {
    lines.push('No quality dimensions were evaluated for the selected scope.');
    lines.push('');
    return lines.join('\n');
  }
  lines.push('| Dimension | Evaluations | PASS | FAIL | WARN | UNKNOWN | N/A | ERROR | Findings |');
  lines.push('|---|---:|---:|---:|---:|---:|---:|---:|---:|');
  for (const d of report.dimensions) {
    lines.push(
      `| ${escapeTableCell(d.dimension)} | ${d.evaluations} | ${d.pass} | ${d.fail} | ${d.warn} | ${d.unknown} | ${d.notApplicable} | ${d.error} | ${d.findings} |`,
    );
  }
  lines.push('');
  return lines.join('\n');
}

// ─── §17-18 Visual Texture ─────────────────────────────────────────

export function renderVisualTexture(report: UIQualityReport): string {
  const lines: string[] = [];
  lines.push('## 5. Visual Texture');
  lines.push('');
  // Visual texture dimensions are rendered from dimension data if available.
  // The 7 fixed visual texture dimensions per §17.
  const vtDims = [
    { key: 'SURFACE', label: 'Surface' },
    { key: 'DEPTH', label: 'Depth' },
    { key: 'COLOR', label: 'Color' },
    { key: 'TYPOGRAPHY', label: 'Typography' },
    { key: 'SPATIAL', label: 'Spatial' },
    { key: 'MOTION', label: 'Motion' },
    { key: 'MICRO_DETAIL', label: 'Micro Detail' },
  ];
  let idx = 1;
  for (const vt of vtDims) {
    lines.push(`### 5.${idx} ${vt.label}`);
    lines.push('');
    const dim = report.dimensions.find((d) => d.dimension === vt.key);
    if (dim) {
      lines.push('#### Evidence');
      lines.push('');
      lines.push(`- ${dim.evaluations} evaluations`);
      lines.push(`- ${dim.unknown} UNKNOWN`);
      lines.push('');
      lines.push('#### Evaluation');
      lines.push('');
      lines.push('| State | Count |');
      lines.push('|---|---:|');
      lines.push(`| PASS | ${dim.pass} |`);
      lines.push(`| FAIL | ${dim.fail} |`);
      lines.push(`| WARN | ${dim.warn} |`);
      lines.push(`| UNKNOWN | ${dim.unknown} |`);
    } else {
      lines.push('No measurements available for this dimension.');
    }
    lines.push('');
    idx++;
  }
  return lines.join('\n');
}

// ─── §19-21 Findings ───────────────────────────────────────────────

export function renderFindings(report: UIQualityReport): string {
  const lines: string[] = [];
  lines.push('## 6. Findings');
  lines.push('');
  if (report.findings.length === 0) {
    lines.push('No findings were generated for the selected scope.');
    lines.push('');
    return lines.join('\n');
  }
  lines.push('| ID | Type | Severity | Subject | Rule | State |');
  lines.push('|---|---|---|---|---|---|');
  for (const f of report.findings) {
    lines.push(
      `| ${escapeTableCell(f.id)} | ${escapeTableCell(f.findingType)} | ${escapeTableCell(f.severity)} | ${escapeTableCell(f.subjectId)} | ${escapeTableCell(f.ruleId)} | ${escapeTableCell(f.state)} |`,
    );
  }
  lines.push('');
  // Finding details
  for (const f of report.findings) {
    lines.push(`### ${escapeMarkdown(f.id)}`);
    lines.push('');
    lines.push(`**State:** ${escapeMarkdown(f.state)}`);
    lines.push('');
    lines.push(`**Severity:** ${escapeMarkdown(f.severity)}`);
    lines.push('');
    lines.push(`**Subject:** \`${escapeMarkdown(f.subjectId)}\``);
    lines.push('');
    lines.push(`**Rule:** \`${escapeMarkdown(f.ruleId)}@${escapeMarkdown(f.ruleVersion)}\``);
    lines.push('');
  }
  return lines.join('\n');
}

// ─── §22-24 Diagnostics ────────────────────────────────────────────

export function renderDiagnostics(report: UIQualityReport): string {
  const lines: string[] = [];
  lines.push('## 7. Diagnostics');
  lines.push('');
  if (report.diagnostics.length === 0) {
    lines.push('No diagnostics were generated for the selected scope.');
    lines.push('');
    return lines.join('\n');
  }
  for (const d of report.diagnostics) {
    lines.push(`### ${escapeMarkdown(d.id)}`);
    lines.push('');
    lines.push(`**Finding:** ${escapeMarkdown(d.findingId)}`);
    lines.push('');
    lines.push(`**Cause:** \`${escapeMarkdown(d.cause)}\``);
    lines.push('');
    lines.push(`**Confidence:** ${escapeMarkdown(d.confidence)}`);
    lines.push('');
    lines.push(escapeMarkdown(d.explanation));
    lines.push('');
  }
  return lines.join('\n');
}

// ─── §30-31 Conformance ────────────────────────────────────────────

export function renderConformance(report: UIQualityReport): string {
  const lines: string[] = [];
  lines.push('## 8. Conformance');
  lines.push('');
  if (!report.conformance) {
    lines.push('Conformance evaluation was not performed for the selected scope.');
    lines.push('');
    return lines.join('\n');
  }
  const c = report.conformance;
  lines.push(`**Level:** ${escapeMarkdown(c.level)}`);
  lines.push('');
  lines.push(`**Status:** ${c.failed === 0 && c.errors === 0 ? 'PASS' : 'FAIL'}`);
  lines.push('');
  lines.push('| Category | Passed | Failed |');
  lines.push('|---|---:|---:|');
  lines.push(`| Total | ${c.passed} | ${c.failed} |`);
  lines.push(`| Unknown | ${c.unknown} | — |`);
  lines.push(`| Errors | ${c.errors} | — |`);
  lines.push('');
  return lines.join('\n');
}

// ─── §28-29 Regression ─────────────────────────────────────────────

export function renderRegression(report: UIQualityReport): string {
  const lines: string[] = [];
  lines.push('## 9. Regression Analysis');
  lines.push('');
  if (!report.regression) {
    lines.push('Regression analysis was not performed for the selected scope.');
    lines.push('');
    return lines.join('\n');
  }
  const r = report.regression.summary;
  lines.push('| Category | Count |');
  lines.push('|---|---:|');
  lines.push(`| NEW_FAILURE | ${r.newFailures} |`);
  lines.push(`| FIXED_FAILURE | ${r.fixedFailures} |`);
  lines.push(`| PERSISTING_FAILURE | ${r.persistingFailures} |`);
  lines.push(`| CHANGED_RESULT | ${r.changedResults} |`);
  lines.push(`| NEW_UNKNOWN | ${r.newUnknowns} |`);
  lines.push(`| RESOLVED_UNKNOWN | ${r.resolvedUnknowns} |`);
  lines.push('');
  // Regression detail: new failures (ADDED = new in current)
  const newFailures = report.regression.findingChanges.filter((fc) => fc.status === 'ADDED');
  if (newFailures.length > 0) {
    lines.push('### New Failures');
    lines.push('');
    for (const fc of newFailures) {
      const subject = fc.after?.subjectId ?? fc.logicKey;
      lines.push(`- ${escapeMarkdown(subject)}`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

// ─── §25-26 Recommendations ────────────────────────────────────────

export function renderRecommendations(report: UIQualityReport): string {
  const lines: string[] = [];
  lines.push('## 10. Improvement Recommendations');
  lines.push('');
  if (report.recommendations.length === 0) {
    lines.push('No improvement recommendations were generated for the selected scope.');
    lines.push('');
    return lines.join('\n');
  }
  for (const r of report.recommendations) {
    lines.push(`### ${escapeMarkdown(r.id)} — ${escapeMarkdown(r.title)}`);
    lines.push('');
    lines.push(`**Dimension:** ${escapeMarkdown(r.dimension)}`);
    lines.push('');
    lines.push(`**Target:** ${escapeMarkdown(r.targetType)}`);
    lines.push('');
    lines.push('**Why**');
    lines.push('');
    lines.push(escapeMarkdown(r.rationale));
    lines.push('');
    lines.push('**Evidence**');
    lines.push('');
    lines.push(`- ${r.evidence.length} evidence references`);
    lines.push(`- ${r.targetIds.length} targets`);
    lines.push('');
    lines.push('**Impact**');
    lines.push('');
    lines.push('Potentially affects:');
    lines.push('');
    lines.push(`- ${r.impact.affectedElements} elements`);
    lines.push(`- ${r.impact.affectedComponents} components`);
    lines.push(`- ${r.impact.affectedThemes.length} themes`);
    lines.push('');
    if (r.verification.length > 0) {
      lines.push('**Verification**');
      lines.push('');
      lines.push('Remeasure the affected components and compare regression results.');
      lines.push('');
    }
  }
  return lines.join('\n');
}

// ─── §27 Verification ──────────────────────────────────────────────

export function renderVerification(report: UIQualityReport): string {
  const lines: string[] = [];
  lines.push('## 11. Verification Criteria');
  lines.push('');
  const criteria = report.recommendations.flatMap((r) =>
    r.verification.map((c) => ({ recommendationId: r.id, ...c })),
  );
  if (criteria.length === 0) {
    lines.push('No verification criteria were generated for the selected scope.');
    lines.push('');
    return lines.join('\n');
  }
  lines.push('| ID | Target | Metric | Rule | Expected |');
  lines.push('|---|---|---|---|---|');
  let idx = 1;
  for (const c of criteria) {
    lines.push(
      `| V-${String(idx).padStart(3, '0')} | ${escapeTableCell(c.recommendationId)} | ${escapeTableCell(c.metricId)} | ${escapeTableCell(c.ruleId)} | ${escapeTableCell(c.expectedState)} |`,
    );
    idx++;
  }
  lines.push('');
  return lines.join('\n');
}

// ─── §32 Release Gate ──────────────────────────────────────────────

export function renderReleaseGate(report: UIQualityReport): string {
  const lines: string[] = [];
  lines.push('## 12. Release Gate');
  lines.push('');
  // Release gate is derived from report facts (not re-evaluated).
  const highFindings = report.findings.filter((f) => f.severity === 'HIGH');
  const newFailures = report.regression?.summary.newFailures ?? 0;
  const conformancePass =
    report.conformance !== undefined && report.conformance.failed === 0 && report.conformance.errors === 0;

  let status: 'PASS' | 'WARN' | 'FAIL';
  if (highFindings.length > 0 || newFailures > 0) {
    status = highFindings.length > 2 ? 'FAIL' : 'WARN';
  } else if (report.findings.length === 0) {
    status = 'PASS';
  } else {
    status = 'WARN';
  }

  lines.push(`**Status:** ${status}`);
  lines.push('');
  lines.push('### Reasons');
  lines.push('');
  if (highFindings.length > 0) {
    lines.push(`- ${highFindings.length} HIGH severity findings`);
  }
  if (newFailures > 0) {
    lines.push(`- ${newFailures} NEW_FAILURE`);
  }
  if (conformancePass) {
    lines.push(`- ${report.conformance!.level} conformance completed`);
  }
  if (highFindings.length === 0 && newFailures === 0 && !conformancePass) {
    lines.push('- No blocking issues detected');
  }
  lines.push('');
  return lines.join('\n');
}

// ─── §33 Reproducibility ───────────────────────────────────────────

export function renderReproducibility(report: UIQualityReport): string {
  const lines: string[] = [];
  lines.push('## 13. Reproducibility');
  lines.push('');
  lines.push('| Property | Value |');
  lines.push('|---|---|');
  lines.push(
    `| Engine | ${escapeTableCell(report.reproducibility.engine.name)} ${escapeTableCell(report.reproducibility.engine.version)} |`,
  );
  lines.push(
    `| Snapshot | ${escapeTableCell(report.scope.snapshotIds.length > 0 ? report.scope.snapshotIds.join(', ') : 'N/A')} |`,
  );
  lines.push(
    `| Viewport | ${escapeTableCell(report.scope.viewports.length > 0 ? report.scope.viewports.join(', ') : 'N/A')} |`,
  );
  lines.push(
    `| Theme | ${escapeTableCell(report.scope.themes.length > 0 ? report.scope.themes.join(', ') : 'N/A')} |`,
  );
  lines.push(`| Metric Versions | ${escapeTableCell(joinList(report.reproducibility.metricVersions))} |`);
  lines.push(`| Rule Versions | ${escapeTableCell(joinList(report.reproducibility.ruleVersions))} |`);
  if (report.reproducibility.configuration) {
    lines.push(
      `| Configuration Hash | ${escapeTableCell(JSON.stringify(report.reproducibility.configuration))} |`,
    );
  }
  lines.push('');
  return lines.join('\n');
}
