/**
 * HTML 报告模板（IMPL-32 §37）。
 *
 * 结构：
 * <main>
 *   <header> Report Metadata </header>
 *   <section> Executive Summary </section>
 *   <section> Quality Dimensions </section>
 *   <section> Visual Texture </section>
 *   <section> Findings </section>
 *   <section> Diagnostics </section>
 *   <section> Recommendations </section>
 *   <section> Verification </section>
 *   <section> Regression </section>
 *   <section> Conformance </section>
 *   <section> Release Gate </section>
 * </main>
 *
 * 所有用户内容经 escapeHtml 转义（§59）。
 */
import type { UIQualityReport } from '../../model/report';
import { escapeHtml } from './escape-html';

function stateBadge(state: string): string {
  const cls =
    state === 'PASS'
      ? 'uiq-badge uiq-badge-pass'
      : state === 'FAIL'
        ? 'uiq-badge uiq-badge-fail'
        : state === 'WARN'
          ? 'uiq-badge uiq-badge-warn'
          : 'uiq-badge uiq-badge-unknown';
  return `<span class="${cls}">${escapeHtml(state)}</span>`;
}

function section(id: string, title: string, body: string): string {
  return `<section id="${escapeHtml(id)}" class="uiq-section" aria-labelledby="heading-${escapeHtml(id)}"><h2 id="heading-${escapeHtml(id)}">${escapeHtml(title)}</h2>${body}</section>`;
}

function emptyMessage(msg: string): string {
  return `<p class="uiq-empty">${escapeHtml(msg)}</p>`;
}

function table(headers: readonly string[], rows: readonly (readonly string[])[]): string {
  const ths = headers.map((h) => `<th scope="col">${escapeHtml(h)}</th>`).join('');
  const trs = rows
    .map((row) => `<tr>${row.map((cell) => `<td>${escapeHtml(cell)}</td>`).join('')}</tr>`)
    .join('');
  return `<table><thead><tr>${ths}</tr></thead><tbody>${trs}</tbody></table>`;
}

// ─── Sections ──────────────────────────────────────────────────────

function renderHeaderHtml(): string {
  return `<header><h1>UI Quality Assessment Report</h1><blockquote>Generated by UIQ 1.0.0</blockquote></header>`;
}

function renderMetadataHtml(report: UIQualityReport): string {
  const rows = [
    ['Project', report.projectId],
    ['UIQ Version', report.version],
    ['Engine Version', report.reproducibility.engine.version],
    [
      'Viewport',
      report.scope.viewports.length > 0 ? report.scope.viewports.join(', ') : 'N/A',
    ],
    ['Theme', report.scope.themes.length > 0 ? report.scope.themes.join(', ') : 'N/A'],
    [
      'Snapshot',
      report.scope.snapshotIds.length > 0 ? report.scope.snapshotIds.join(', ') : 'N/A',
    ],
    ['Generated At', report.generatedAt],
  ];
  return section('metadata', '1. Report Metadata', table(['Property', 'Value'], rows));
}

function renderSummaryHtml(report: UIQualityReport): string {
  const s = report.summary;
  const scopeBody = `<ul>
<li>Pages: ${report.scope.snapshotIds.length}</li>
<li>Elements: ${s.measuredElements}</li>
<li>Components: ${report.scope.subjects.length}</li>
<li>Themes: ${report.scope.themes.length}</li>
</ul>`;
  const evalBody = table(
    ['State', 'Count'],
    [
      ['PASS', String(s.pass)],
      ['FAIL', String(s.fail)],
      ['WARN', String(s.warn)],
      ['UNKNOWN', String(s.unknown)],
      ['NOT_APPLICABLE', String(s.notApplicable)],
      ['ERROR', String(s.error)],
    ],
  );
  return section('summary', '2. Executive Summary', `<h3>Scope</h3>${scopeBody}<h3>Evaluation</h3>${evalBody}`);
}

function renderCoverageHtml(report: UIQualityReport): string {
  if (report.dimensions.length === 0) {
    return section('coverage', '3. Measurement Coverage', emptyMessage('No measurement coverage data available.'));
  }
  const rows = report.dimensions.map((d) => {
    const total = d.evaluations;
    const coverage = total > 0 ? (((total - d.unknown) / total) * 100).toFixed(1) + '%' : '100.0%';
    return [d.dimension, String(d.evaluations), String(d.evaluations), String(d.unknown), coverage];
  });
  return section(
    'coverage',
    '3. Measurement Coverage',
    table(['Dimension', 'Elements', 'Measurements', 'Unknown', 'Coverage'], rows),
  );
}

function renderDimensionsHtml(report: UIQualityReport): string {
  if (report.dimensions.length === 0) {
    return section('dimensions', '4. Quality Dimensions', emptyMessage('No quality dimensions were evaluated.'));
  }
  const rows = report.dimensions.map((d) => [
    d.dimension,
    String(d.evaluations),
    String(d.pass),
    String(d.fail),
    String(d.warn),
    String(d.unknown),
    String(d.notApplicable),
    String(d.error),
    String(d.findings),
  ]);
  return section(
    'dimensions',
    '4. Quality Dimensions',
    table(
      ['Dimension', 'Evaluations', 'PASS', 'FAIL', 'WARN', 'UNKNOWN', 'N/A', 'ERROR', 'Findings'],
      rows,
    ),
  );
}

function renderVisualTextureHtml(report: UIQualityReport): string {
  const vtDims = [
    { key: 'SURFACE', label: 'Surface' },
    { key: 'DEPTH', label: 'Depth' },
    { key: 'COLOR', label: 'Color' },
    { key: 'TYPOGRAPHY', label: 'Typography' },
    { key: 'SPATIAL', label: 'Spatial' },
    { key: 'MOTION', label: 'Motion' },
    { key: 'MICRO_DETAIL', label: 'Micro Detail' },
  ];
  let body = '';
  for (const vt of vtDims) {
    const dim = report.dimensions.find((d) => d.dimension === vt.key);
    body += `<h3>${escapeHtml(vt.label)}</h3>`;
    if (dim) {
      body += `<p>${dim.evaluations} evaluations, ${dim.unknown} UNKNOWN</p>`;
      body += table(
        ['State', 'Count'],
        [
          ['PASS', String(dim.pass)],
          ['FAIL', String(dim.fail)],
          ['WARN', String(dim.warn)],
          ['UNKNOWN', String(dim.unknown)],
        ],
      );
    } else {
      body += emptyMessage('No measurements available for this dimension.');
    }
  }
  return section('visual-texture', '5. Visual Texture', body);
}

function renderFindingsHtml(report: UIQualityReport): string {
  if (report.findings.length === 0) {
    return section('findings', '6. Findings', emptyMessage('No findings were generated for the selected scope.'));
  }
  const rows = report.findings.map((f) => [f.id, f.findingType, f.severity, f.subjectId, f.ruleId, f.state]);
  let body = table(['ID', 'Type', 'Severity', 'Subject', 'Rule', 'State'], rows);
  // Expandable finding details
  for (const f of report.findings) {
    body += `<details><summary>${escapeHtml(f.id)}</summary>
<p><strong>State:</strong> ${stateBadge(f.state)}</p>
<p><strong>Severity:</strong> ${escapeHtml(f.severity)}</p>
<p><strong>Subject:</strong> <code>${escapeHtml(f.subjectId)}</code></p>
<p><strong>Rule:</strong> <code>${escapeHtml(f.ruleId)}@${escapeHtml(f.ruleVersion)}</code></p>
</details>`;
  }
  return section('findings', '6. Findings', body);
}

function renderDiagnosticsHtml(report: UIQualityReport): string {
  if (report.diagnostics.length === 0) {
    return section('diagnostics', '7. Diagnostics', emptyMessage('No diagnostics were generated.'));
  }
  let body = '';
  for (const d of report.diagnostics) {
    body += `<details><summary>${escapeHtml(d.id)}</summary>
<p><strong>Finding:</strong> ${escapeHtml(d.findingId)}</p>
<p><strong>Cause:</strong> <code>${escapeHtml(d.cause)}</code></p>
<p><strong>Confidence:</strong> ${escapeHtml(d.confidence)}</p>
<p>${escapeHtml(d.explanation)}</p>
</details>`;
  }
  return section('diagnostics', '7. Diagnostics', body);
}

function renderConformanceHtml(report: UIQualityReport): string {
  if (!report.conformance) {
    return section('conformance', '8. Conformance', emptyMessage('Conformance evaluation was not performed.'));
  }
  const c = report.conformance;
  const status = c.failed === 0 && c.errors === 0 ? 'PASS' : 'FAIL';
  const body = `<p><strong>Level:</strong> ${escapeHtml(c.level)}</p>
<p><strong>Status:</strong> ${stateBadge(status)}</p>
${table(['Category', 'Passed', 'Failed'], [
  ['Total', String(c.passed), String(c.failed)],
  ['Unknown', String(c.unknown), '—'],
  ['Errors', String(c.errors), '—'],
])}`;
  return section('conformance', '8. Conformance', body);
}

function renderRegressionHtml(report: UIQualityReport): string {
  if (!report.regression) {
    return section('regression', '9. Regression Analysis', emptyMessage('Regression analysis was not performed.'));
  }
  const r = report.regression.summary;
  let body = table(
    ['Category', 'Count'],
    [
      ['NEW_FAILURE', String(r.newFailures)],
      ['FIXED_FAILURE', String(r.fixedFailures)],
      ['PERSISTING_FAILURE', String(r.persistingFailures)],
      ['CHANGED_RESULT', String(r.changedResults)],
      ['NEW_UNKNOWN', String(r.newUnknowns)],
      ['RESOLVED_UNKNOWN', String(r.resolvedUnknowns)],
    ],
  );
  const added = report.regression.findingChanges.filter((fc) => fc.status === 'ADDED');
  if (added.length > 0) {
    body += '<h3>New Failures</h3><ul>';
    for (const fc of added) {
      const subject = fc.after?.subjectId ?? fc.logicKey;
      body += `<li>${escapeHtml(subject)}</li>`;
    }
    body += '</ul>';
  }
  return section('regression', '9. Regression Analysis', body);
}

function renderRecommendationsHtml(report: UIQualityReport): string {
  if (report.recommendations.length === 0) {
    return section(
      'recommendations',
      '10. Improvement Recommendations',
      emptyMessage('No improvement recommendations were generated.'),
    );
  }
  let body = '';
  for (const r of report.recommendations) {
    body += `<details><summary>${escapeHtml(r.id)} — ${escapeHtml(r.title)}</summary>
<p><strong>Dimension:</strong> ${escapeHtml(r.dimension)}</p>
<p><strong>Target:</strong> ${escapeHtml(r.targetType)}</p>
<p><strong>Why:</strong> ${escapeHtml(r.rationale)}</p>
<p><strong>Impact:</strong> ${r.impact.affectedElements} elements, ${r.impact.affectedComponents} components, ${r.impact.affectedThemes.length} themes</p>
</details>`;
  }
  return section('recommendations', '10. Improvement Recommendations', body);
}

function renderVerificationHtml(report: UIQualityReport): string {
  const criteria = report.recommendations.flatMap((r) =>
    r.verification.map((c) => [r.id, c.metricId, c.ruleId, c.expectedState] as const),
  );
  if (criteria.length === 0) {
    return section('verification', '11. Verification Criteria', emptyMessage('No verification criteria were generated.'));
  }
  const rows = criteria.map(([recId, metricId, ruleId, expected], i) => [
    `V-${String(i + 1).padStart(3, '0')}`,
    recId,
    metricId,
    ruleId,
    expected,
  ]);
  return section('verification', '11. Verification Criteria', table(['ID', 'Target', 'Metric', 'Rule', 'Expected'], rows));
}

function renderReleaseGateHtml(report: UIQualityReport): string {
  const highFindings = report.findings.filter((f) => f.severity === 'HIGH');
  const newFailures = report.regression?.summary.newFailures ?? 0;
  const conformancePass =
    report.conformance !== undefined && report.conformance.failed === 0 && report.conformance.errors === 0;

  let status: 'PASS' | 'WARN' | 'FAIL';
  if (highFindings.length > 0 || newFailures > 0) {
    status = highFindings.length > 2 ? 'FAIL' : 'WARN';
  } else if (report.findings.length === 0) {
    status = 'PASS';
  } else {
    status = 'WARN';
  }

  const reasons: string[] = [];
  if (highFindings.length > 0) reasons.push(`${highFindings.length} HIGH severity findings`);
  if (newFailures > 0) reasons.push(`${newFailures} NEW_FAILURE`);
  if (conformancePass) reasons.push(`${report.conformance!.level} conformance completed`);
  if (reasons.length === 0) reasons.push('No blocking issues detected');

  const body = `<p><strong>Status:</strong> ${stateBadge(status)}</p>
<h3>Reasons</h3>
<ul>${reasons.map((r) => `<li>${escapeHtml(r)}</li>`).join('')}</ul>`;
  return section('release-gate', '12. Release Gate', body);
}

function renderReproducibilityHtml(report: UIQualityReport): string {
  const joinList = (items: readonly string[]): string => (items.length > 0 ? items.join(', ') : 'none');
  const rows = [
    ['Engine', `${report.reproducibility.engine.name} ${report.reproducibility.engine.version}`],
    [
      'Snapshot',
      report.scope.snapshotIds.length > 0 ? report.scope.snapshotIds.join(', ') : 'N/A',
    ],
    [
      'Viewport',
      report.scope.viewports.length > 0 ? report.scope.viewports.join(', ') : 'N/A',
    ],
    ['Theme', report.scope.themes.length > 0 ? report.scope.themes.join(', ') : 'N/A'],
    ['Metric Versions', joinList(report.reproducibility.metricVersions)],
    ['Rule Versions', joinList(report.reproducibility.ruleVersions)],
  ];
  return section('reproducibility', '13. Reproducibility', table(['Property', 'Value'], rows));
}

// ─── Assemble ──────────────────────────────────────────────────────

export function assembleHtml(report: UIQualityReport, stylesheet: string): string {
  return [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    `<title>UIQ Quality Report — ${escapeHtml(report.projectId)}</title>`,
    stylesheet,
    '</head>',
    '<body>',
    '<main>',
    renderHeaderHtml(),
    renderMetadataHtml(report),
    renderSummaryHtml(report),
    renderCoverageHtml(report),
    renderDimensionsHtml(report),
    renderVisualTextureHtml(report),
    renderFindingsHtml(report),
    renderDiagnosticsHtml(report),
    renderConformanceHtml(report),
    renderRegressionHtml(report),
    renderRecommendationsHtml(report),
    renderVerificationHtml(report),
    renderReleaseGateHtml(report),
    renderReproducibilityHtml(report),
    '</main>',
    '</body>',
    '</html>',
  ].join('\n');
}
