import type { EnrichedRuleDefinition } from '../../evaluation/engine';
import { DEPTH_ELEVATION_RULE, DEPTH_SHADOW_DEPTH_RULE, DEPTH_LAYER_RULE, DEPTH_SEPARATION_RULE, DEPTH_OVERLAY_RULE, DEPTH_SPATIAL_PRIORITY_RULE } from './rules';

export const depthRules: readonly EnrichedRuleDefinition[] = [
  DEPTH_ELEVATION_RULE, DEPTH_SHADOW_DEPTH_RULE, DEPTH_LAYER_RULE,
  DEPTH_SEPARATION_RULE, DEPTH_OVERLAY_RULE, DEPTH_SPATIAL_PRIORITY_RULE,
] as const;

export { DEPTH_ELEVATION_RULE, DEPTH_SHADOW_DEPTH_RULE, DEPTH_LAYER_RULE, DEPTH_SEPARATION_RULE, DEPTH_OVERLAY_RULE, DEPTH_SPATIAL_PRIORITY_RULE };
