import type { EnrichedRuleDefinition } from '../../evaluation/engine';
import {
  TYPO_FONT_CONSISTENCY_RULE, TYPO_SCALE_CONSISTENCY_RULE, TYPO_WEIGHT_HIERARCHY_RULE,
  TYPO_LINEHEIGHT_RHYTHM_RULE, TYPO_SPACING_QUALITY_RULE, TYPO_DENSITY_BALANCE_RULE,
  TYPO_HIERARCHY_RULE,
} from './rules';

export const typographyTextureRules: readonly EnrichedRuleDefinition[] = [
  TYPO_FONT_CONSISTENCY_RULE, TYPO_SCALE_CONSISTENCY_RULE, TYPO_WEIGHT_HIERARCHY_RULE,
  TYPO_LINEHEIGHT_RHYTHM_RULE, TYPO_SPACING_QUALITY_RULE, TYPO_DENSITY_BALANCE_RULE,
  TYPO_HIERARCHY_RULE,
] as const;

export {
  TYPO_FONT_CONSISTENCY_RULE, TYPO_SCALE_CONSISTENCY_RULE, TYPO_WEIGHT_HIERARCHY_RULE,
  TYPO_LINEHEIGHT_RHYTHM_RULE, TYPO_SPACING_QUALITY_RULE, TYPO_DENSITY_BALANCE_RULE,
  TYPO_HIERARCHY_RULE,
};
