import type { EnrichedRuleDefinition } from '../../evaluation/engine';
import {
  SPATIAL_GRID_RULE, SPATIAL_ALIGNMENT_RULE, SPATIAL_SPACING_RULE,
  SPATIAL_WHITESPACE_RULE, SPATIAL_DENSITY_RULE, SPATIAL_PROPORTION_RULE,
  SPATIAL_COMPOSITION_RULE,
} from './rules';

export const spatialTextureRules: readonly EnrichedRuleDefinition[] = [
  SPATIAL_GRID_RULE, SPATIAL_ALIGNMENT_RULE, SPATIAL_SPACING_RULE,
  SPATIAL_WHITESPACE_RULE, SPATIAL_DENSITY_RULE, SPATIAL_PROPORTION_RULE,
  SPATIAL_COMPOSITION_RULE,
] as const;

export {
  SPATIAL_GRID_RULE, SPATIAL_ALIGNMENT_RULE, SPATIAL_SPACING_RULE,
  SPATIAL_WHITESPACE_RULE, SPATIAL_DENSITY_RULE, SPATIAL_PROPORTION_RULE,
  SPATIAL_COMPOSITION_RULE,
};
