import type { EnrichedRuleDefinition } from '../../evaluation/engine';
import {
  MOTION_TRANSITION_RULE, MOTION_ANIMATION_TIMING_RULE, MOTION_EASING_RULE,
  MOTION_STATE_CHANGE_RULE, MOTION_CONSISTENCY_RULE, MOTION_LOADING_RULE,
  MOTION_DURATION_CONSISTENCY_RULE,
} from './rules';

export const motionTextureRules: readonly EnrichedRuleDefinition[] = [
  MOTION_TRANSITION_RULE, MOTION_ANIMATION_TIMING_RULE, MOTION_EASING_RULE,
  MOTION_STATE_CHANGE_RULE, MOTION_CONSISTENCY_RULE, MOTION_LOADING_RULE,
  MOTION_DURATION_CONSISTENCY_RULE,
] as const;

export {
  MOTION_TRANSITION_RULE, MOTION_ANIMATION_TIMING_RULE, MOTION_EASING_RULE,
  MOTION_STATE_CHANGE_RULE, MOTION_CONSISTENCY_RULE, MOTION_LOADING_RULE,
  MOTION_DURATION_CONSISTENCY_RULE,
};
