export {
  SURFACE_RADIUS_CONSISTENCY_RULE,
  SURFACE_RADIUS_FRAGMENTATION_RULE,
  SURFACE_BORDER_CONSISTENCY_RULE,
  SURFACE_SHADOW_CONSISTENCY_RULE,
  SURFACE_SHADOW_COMPLEXITY_RULE,
  SURFACE_LAYER_CONSISTENCY_RULE,
  SURFACE_TRANSPARENCY_CONSISTENCY_RULE,
  SURFACE_MATERIAL_CONSISTENCY_RULE,
  surfaceRules,
} from './surface';

export {
  DEPTH_ELEVATION_RULE,
  DEPTH_SHADOW_DEPTH_RULE,
  DEPTH_LAYER_RULE,
  DEPTH_SEPARATION_RULE,
  DEPTH_OVERLAY_RULE,
  DEPTH_SPATIAL_PRIORITY_RULE,
  depthRules,
} from './depth';

export {
  COLOR_LIGHTNESS_HIERARCHY_RULE,
  COLOR_CHROMA_DISTRIBUTION_RULE,
  COLOR_HUE_RELATIONSHIP_RULE,
  COLOR_HARMONY_RULE,
  COLOR_TOKEN_CONSISTENCY_RULE,
  COLOR_NOISE_RULE,
  COLOR_CONTRAST_QUALITY_RULE,
  colorTextureRules,
} from './color-texture';

export {
  TYPO_FONT_CONSISTENCY_RULE,
  TYPO_SCALE_CONSISTENCY_RULE,
  TYPO_WEIGHT_HIERARCHY_RULE,
  TYPO_LINEHEIGHT_RHYTHM_RULE,
  TYPO_SPACING_QUALITY_RULE,
  TYPO_DENSITY_BALANCE_RULE,
  TYPO_HIERARCHY_RULE,
  typographyTextureRules,
} from './typography';

export {
  SPATIAL_GRID_RULE,
  SPATIAL_ALIGNMENT_RULE,
  SPATIAL_SPACING_RULE,
  SPATIAL_WHITESPACE_RULE,
  SPATIAL_DENSITY_RULE,
  SPATIAL_PROPORTION_RULE,
  SPATIAL_COMPOSITION_RULE,
  spatialTextureRules,
} from './spatial';

export {
  MOTION_TRANSITION_RULE,
  MOTION_ANIMATION_TIMING_RULE,
  MOTION_EASING_RULE,
  MOTION_STATE_CHANGE_RULE,
  MOTION_CONSISTENCY_RULE,
  MOTION_LOADING_RULE,
  MOTION_DURATION_CONSISTENCY_RULE,
  motionTextureRules,
} from './motion';

export {
  MICRO_STATE_COMPLETENESS_RULE,
  MICRO_COMPONENT_CONSISTENCY_RULE,
  MICRO_ICON_CONSISTENCY_RULE,
  MICRO_FOCUS_QUALITY_RULE,
  MICRO_DISABLED_QUALITY_RULE,
  MICRO_EMPTY_QUALITY_RULE,
  MICRO_BORDER_DETAIL_RULE,
  MICRO_RADIUS_DETAIL_RULE,
  MICRO_LOADING_QUALITY_RULE,
  MICRO_ERROR_QUALITY_RULE,
  MICRO_HOVER_COMPLETENESS_RULE,
  MICRO_ACTIVE_FEEDBACK_RULE,
  MICRO_SELECTED_DIFFERENTIATION_RULE,
  MICRO_ICON_ALIGNMENT_RULE,
  MICRO_COMPONENT_DENSITY_RULE,
  MICRO_FRAGMENTATION_RULE,
  microDetailTextureRules,
} from './micro-detail';

export {
  createVisualTextureRuleRegistry,
  type VisualTextureRuleRegistry,
} from './registry';
